### PR TITLE
#557 & #560: create callback generator for dAPI errors that occur during normal operations

### LINKED ISSUE #557: Catch 403s after DMs
If a bot DMs a user who's blocked it, a 403 will be returned, so all DMs should catch and ignore those to avoid crashing. Consider making a wrapper so that it can be added to the bot template.

### LINKED ISSUE #560: Implement `butIgnoreCantSendToThisUserErrors` in relevant places
See #558

### PR DESCRIPTION
**Pull request by ntseng**
Summary
-------
- created `butIgnoreDiscordInteractionCollectorErrors()` to consolidate handling of interaction collector timeouts
- created `butIgnoreMissingPermissionErrors()` to consolidate handling missing permissions for side-effects

Local Tests Performed
---------------------
- [x] bot still turns on (no build errors, circular dependencies, or start-up errors)
- [x] let modal time out on `/feedback`: bug report (set duration to 3 ms) and confirmed that callback was called (added console log to callback) and bot didn't crash
- [x] fixed circular dependency

Issue
-----
Closes #557, Closes #560

### CODE REVIEW

File: source/frontend/shared/dAPIResponses.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+const { DiscordjsErrorCodes } = require("discord.js");
+
+/** @param {(error) => boolean} ignoreThese */
+function butIgnoreCertainErrors(ignoreThese) {
+	return (error) => {
+		if (!ignoreThese(error)) {
+			console.error(error);
+		}
+	}
+}
```
Comment (SillySalamndr) [inline source/frontend/shared/dAPIResponses.js]: Allowing this to take in any number of functions would be a minor but useful quality of life for composing multiple errors into one check in the future.
```suggestion
function butIgnoreCertainErrors(...ignoreThese) {
	return (error) => {
		for (const ignoreThis of ignoreThese) {
			if (ignoreThis(error)) {
				return;
			}
		}
		console.error(error);
	}
}
```
